/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lizon
 */

import com.sun.corba.se.impl.oa.toa.TOAImpl;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import sun.security.timestamp.TimestampToken;
//jhcuse---------------
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.ansj.domain.Result;
import org.ansj.domain.Term;
import org.ansj.splitWord.analysis.ToAnalysis;
import SearchNLP
//------------

@ManagedBean(name = "searchTest")
@SessionScoped
public class SearchTest implements Serializable {
    //数据库信息
    private static final sqlUser = "root";
    private static final sqlPw = "jhczxcvbnm";

    // 超参数常量区
    private static final long serialVersionUID = 1L; 
    public Integer MESSAGE_PER_PAGE = 6; //每一页显示数量
    public void setMessagePerPage(Integer MESSAGE_PER_PAGE) {
        this.MESSAGE_PER_PAGE = MESSAGE_PER_PAGE;
    }
    public Integer getMessagePerPage() {
        return MESSAGE_PER_PAGE;
    }
    // 网站一些变量区
    public static Integer CURRENT_PAGE = 1; //当前页数
    public static Integer pages_num = 27; // 总消息数目
    public Double searchtime = new Double(0.012312);    // 搜索时间
    // 还没有过的老金变量区
    public String universalVariable;
    public String searchContent;
    // 网站一些变量区的getset方法
    public void setPagesNum(Integer pages_num) {
        this.pages_num = pages_num;
    }
    public Integer getPagesNum() {
        return pages_num;
    }
    public String getPagesNumString(){
        return pages_num.toString();
    }
    
    public Double getSearchTime() {
        return searchtime;
    }
    public void setSearchTime(Double searchtime) {
        this.searchtime = searchtime;
    }
    public String getSearchTimeString() {
        return searchtime.toString();
    }
    
    private static final ArrayList<Message> messageList
            = new ArrayList<Message>(Arrays.asList(
                    new Message("1  021333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("2  11333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("3  21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("4 213333332131<em>231232</em>13123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("5 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("6 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("7 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("8 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("9 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("10 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("11 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("12 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("13 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("14 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("15 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("16 13333332131<em>231232</em>13123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("17 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("18 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("19 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("20 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("21 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("22 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("23 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("24 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("25 21333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("26 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1),
                    new Message("27 1333333213123123213123123sfsdgwfvsadfce", "CSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAFDAFCSASSSSSSSS<em>SSSSSSDAFDSF重点S</em>SSSSSSSSSSSSSDAF", "https://www.baidu.com", 1)
            ));


    //获取消息体get方法
    public List<Message> getMessageList() {
        System.out.println((CURRENT_PAGE - 1) * MESSAGE_PER_PAGE + "    " + (CURRENT_PAGE) * (MESSAGE_PER_PAGE));
        if((CURRENT_PAGE) * (MESSAGE_PER_PAGE)<=pages_num){
            return messageList.subList((CURRENT_PAGE - 1) * MESSAGE_PER_PAGE, (CURRENT_PAGE) * (MESSAGE_PER_PAGE));
        }
        else{
            return messageList.subList((CURRENT_PAGE - 1) * MESSAGE_PER_PAGE, pages_num);
        }
    }
    //单体结构消息体类
    public static class Message {

        String title;
        String context;
        String url;

        public Message(String title, String context, String url) {
            this.title = title;
            this.context = context;
            this.url = url;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public String getContext() {
            return context;
        }

        public void setContext(String context) {
            this.context = context;
        }

        public String getUrl() {
            return url;
        }

        public void setUrl(String url) {
            this.url = url;
        }
    }

    //选择界面所存放的变量
    public ArrayList<Selectpagelistall> selectpage;
    //选择界面的类，定义了循环内部的方法
    public class Selectpagelistall {

        String selectpagelist;
        String spantag;
        String herftag;
        public Selectpagelistall(String selectpagelist, String spantag, String herftag) {
            this.selectpagelist = selectpagelist;
            this.spantag = spantag;
            this.herftag = herftag;
        }

        public String getSelectPageList() {

            return selectpagelist;
        }

        public void setSelectPageList(String selectpagelist) {
            this.selectpagelist = selectpagelist;
        }

        public String getSpanTag() {
            return spantag;
        }

        public void setSpanTag(String spantag) {
            this.spantag = spantag;
        }
        
        public String getHerfTag() {
            return herftag;
        }

        public void setHerfTag(String herftag) {
            this.herftag = herftag;
        }
    }
    //选择界面get函数，不需要修改
    public List<Selectpagelistall> getSelectPage(){
        selectpage = new ArrayList<Selectpagelistall>();
            int pages = pages_num/MESSAGE_PER_PAGE+1;
            int i;
            if (pages < 10) {
                for (i = 1; i <= pages; i++) {
                        Selectpagelistall test;
                        if(i == CURRENT_PAGE){
                            test = new Selectpagelistall("pc current-page",i+"",i+"");
                        }
                        else{
                            test = new Selectpagelistall("pc",i+"",i+"");
                        }
                    selectpage.add(test);
                }
            } else {
                if (CURRENT_PAGE <= 5) {
                    for (i = 1; i <= 10; i++) {
                        Selectpagelistall test;
                        if(i == CURRENT_PAGE){
                            test = new Selectpagelistall("pc current-page",i+"",i+"");
                        }
                        else{
                            test = new Selectpagelistall("pc",i+"",i+"");
                        }
                        selectpage.add(test);
                    }
                } else if (CURRENT_PAGE >= pages - 4) {
                    for (i = pages - 9; i <= pages; i++) {
                        Selectpagelistall test;
                        if(i == CURRENT_PAGE){
                            test = new Selectpagelistall("pc current-page",i+"",i+"");
                        }
                        else{
                            test = new Selectpagelistall("pc",i+"",i+"");
                        }
                        selectpage.add(test);
                    }
                } else {
                    for (i = CURRENT_PAGE - 4; i <= CURRENT_PAGE + 5; i++) {
                        Selectpagelistall test;
                        if(i == CURRENT_PAGE){
                            test = new Selectpagelistall("pc current-page",i+"",i+"");
                        }
                        else{
                            test = new Selectpagelistall("pc",i+"",i+"");
                        }
                        selectpage.add(test);
                    }
                }
            }
            if(CURRENT_PAGE == 1){
                Selectpagelistall last = new Selectpagelistall("pc prompt","后一页",CURRENT_PAGE+1+"");
                selectpage.add(last);
            }
            else if (CURRENT_PAGE == pages){
                Selectpagelistall first = new Selectpagelistall("pc prompt","前一页",CURRENT_PAGE-1+"");
                selectpage.add(0,first);
            }
            else{
                Selectpagelistall last = new Selectpagelistall("pc prompt","后一页",CURRENT_PAGE+1+"");
                selectpage.add(last);
                Selectpagelistall first = new Selectpagelistall("pc prompt","前一页",CURRENT_PAGE-1+"");
                selectpage.add(0,first);
            }
            
            return selectpage;
    }
    
    
    // URL映射专区，不需要修改：start========================================================
    private int param = 1;
    private String searchwd;
    public int getParam() {
        CURRENT_PAGE = param;
        System.err.println("Param  get   param value is "+this.param);
        return param;
    }
    public void setParam(int param) {
        System.err.println("Param  set   param value is "+this.param);
        this.param = param;
    }
 
    public String getSearchwd(){
        System.err.println("searchwd  get "+this.searchwd);
        return searchwd;
    }
    public void setSearchwd(String searchwd){
        System.err.println("searchwd   set "+this.searchwd);
        this.searchwd = searchwd;
    }
    //在这里导入数据！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！，实现相关参数赋值@金，写完了把注释删了嘤嘤嘤
    public void init(){
        CURRENT_PAGE = param; 
        System.err.println("Init           Init           Init           Init           "+this.param);
        //----------------------------------------------------
        Result startNLP = ToAnalysis.parse("1");//无用语句,仅启动NLP
        //----------------------------------------------------
        someThing();//分词,匹配,并将结果写入数据库临时表
        //按序取出结果
        try {
            Map<String,String> resultSearch = new HashMap<String,String>();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buptsearcher?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL",sqlUser,sqlPw);
            String sql = "select * from currentsearch order by page_id desc"; 
            //查询
            Statement stmt2 =con.createStatement();
            ResultSet rs = stmt2.executeQuery(sql);
            while(rs.next()){
                String title = rs.getString("title");
                String url = rs.getString("url");
                String content = rs.getString("content");
                messageList.add(new Message(title,content,url));
            }
        } catch (Exception e) {
            System.err.println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
            System.err.println(e);
            System.err.println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        }
        

    }
    private void someThing(){
        String str = this.searchContent;
        SearchNLP snlp = SearchNLP();
        Map<String,String> contentSQL= new HashMap<String,String>();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/buptsearcher?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL",sqlUser,sqlPw);
            String sql = "select * from websites_info"; 
            //查询
            Statement stmt =con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                String url = rs.getString("url");
                String title = rs.getString("title");
                String content = rs.getString("content");
                String click_times = rs.getString("click_times");

                contentSQL.put("url", url);
                contentSQL.put("title", title);
                contentSQL.put("content", content);
                contentSQL.put("click_times", click_times);
                Map availableURL = snlp.getresult(str,contentSQL);
                System.out.println(availableURL.toString());//----------------------------
                if(availableURL != null){
                    sql = String.format("insert into currentsearch(page_id,title,url,content) values ('%s','%s','%s','%s')",availableURL.get("page_id"),availableURL.get("title"),availableURL.get("url"),availableURL.get("content"));
                    Statement stmt1 =con.createStatement();
                    stmt1.executeUpdate(sql);    
                }
            }

//            System.out.println(a.getresult(str,contentSQL).toString());//NLP+检索
        } catch (Exception e) {
            System.err.println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
            System.err.println(e);
            System.err.println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
        }





    }
    // URL映射专区：end========================================================
   
}
    
