-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 21:29:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bupt_search
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `sex` TINYINT(1) NOT NULL,
  `user_post_date` DATETIME NOT NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`searchlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`searchlog` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `search_word` VARCHAR(45) NOT NULL,
  `time` DATETIME NOT NULL,
  `User_User_id` INT NOT NULL,
  `ip` VARCHAR(25) NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_searchlog_User_idx` (`User_User_id` ASC),
  CONSTRAINT `fk_searchlog_User`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `mydb`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currentsearch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`currentsearch` (
  `order` INT NOT NULL,
  `description` TEXT(1) NOT NULL,
  `searchlog_log_id` INT NOT NULL,
  PRIMARY KEY (`order`, `searchlog_log_id`),
  INDEX `fk_currentsearch_searchlog1_idx` (`searchlog_log_id` ASC),
  CONSTRAINT `fk_currentsearch_searchlog1`
    FOREIGN KEY (`searchlog_log_id`)
    REFERENCES `mydb`.`searchlog` (`log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prefersettings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prefersettings` (
  `background_id` INT NOT NULL,
  `is_use_js` TINYINT NOT NULL,
  `User_User_id` INT NOT NULL,
  INDEX `fk_prefersettings_User1_idx` (`User_User_id` ASC),
  PRIMARY KEY (`User_User_id`),
  CONSTRAINT `fk_prefersettings_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `mydb`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `admin_account` VARCHAR(45) NOT NULL,
  `admin_passwd` VARCHAR(45) NOT NULL,
  `admin_lv` INT NOT NULL,
  PRIMARY KEY (`admin_account`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
